apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 503237308475.dkr.ecr.eu-north-1.amazonaws.com/demo-frontend
  newName: 503237308475.dkr.ecr.eu-north-1.amazonaws.com/demo-frontend
  newTag: "05699447"
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
